//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depo.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMalzeme
    {
        public int ID { get; set; }
        public string urun { get; set; }
        public string fiyat { get; set; }
        public Nullable<int> miktar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> personel { get; set; }
        public Nullable<int> firma { get; set; }
    
        public virtual TblFirmalar TblFirmalar { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
    }
}
